#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause

get_function_by_input() {
  local user_input="$1"

  local suffix=$(echo "$user_input" | tr '[:upper:]' '[:lower:]' | tr ' ' '_')
  echo "change_to_$suffix"
}

s="${BASH_SOURCE[0]}";[[ "$s" ]] || s="${(%):-%N}";while [ -h "$s" ];do d="$(cd -P "$(dirname "$s")" && pwd)";s="$(readlink "$s")";[[ $s != /* ]] && s="$d/$s";done;__DIR__=$(cd -P "$(dirname "$s")" && pwd)

# Validate the input
input="$1"
if [[ ! "$input" ]]; then
  echo "❌ Missing argument - audio configuration name or alias."
  exit 1
fi

CACHE_PATH="${TMPDIR:-${TEMP:-/tmp}}"
CACHE_PATH="${CACHE_PATH%%/}/com.aklump.chaud"
export CACHE_PATH

if [[ "$input" == '-c' ]]; then
  # Flush the cache so new config will be used, if it is changed.
  [[ "$CACHE_PATH" ]] && rm "$CACHE_PATH/"* &>/dev/null

  # Print the config getPath for user to open and edit.
  config_path="$("$__DIR__/bin/get_config_path.php")"
  [ ! -f "$config_path" ] && $("$__DIR__/bin/install_config.php")
  echo "✏️ $config_path"
  exit 0
fi

# (Generate and) load the functions to change the audio by input.
change_functions_path="$CACHE_PATH/change_audio.sh"
[ ! -f "$change_functions_path" ] && "$__DIR__/bin/create_change_functions.php" "$change_functions_path"
source "$change_functions_path"

# Make the change.
change_function=$(get_function_by_input "$input")
! declare -F $change_function > /dev/null && echo "❌ Unknown audio configuration: $input" && exit 1
$change_function
